//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Book()
        {
            this.Tbl_Process = new HashSet<Tbl_Process>();
        }
    
        public int BookID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Category { get; set; }
        public Nullable<short> Writer { get; set; }
        public string Year { get; set; }
        public string PublishingHouse { get; set; }
        public string Page { get; set; }
        public Nullable<bool> Situation { get; set; }
        public string Picture { get; set; }
        public string Summary { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Writer Tbl_Writer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Process> Tbl_Process { get; set; }
    }
}
